### ISSUE TITLE
调用服务超时错误

### ISSUE THREAD

**Issue by mrzjl** [chatbi/chatbi#1]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Promise.then.promptTokens (file:///Users/zhangjianlong/workspace/nhr-2022/nhr-gpt/chatbi-main/node_modules/.pnpm/@aigcaas+chatgpt@5.2.4/node_modules/@aigcaas/chatgpt/src/chatgpt-api.ts:285:25) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8422:28)
      at node:internal/deps/undici/undici:8380:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8411:13)
      at processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
[Nest] 91399  - 07/03/2023, 5:15:07 PM   ERROR [ChatService] TypeError: fetch failed

**Comment by mrzjl** [comment]
> 



> TypeError: fetch failed at Object.fetch (node:internal/deps/undici/undici:11457:11) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Promise.then.promptTokens (file:///Users/zhangjianlong/workspace/nhr-2022/nhr-gpt/chatbi-main/node_modules/.pnpm/@aigcaas+chatgpt@5.2.4/node_modules/@aigcaas/chatgpt/src/chatgpt-api.ts:285:25) { cause: ConnectTimeoutError: Connect Timeout Error at onConnectTimeout (node:internal/deps/undici/undici:8422:28) at node:internal/deps/undici/undici:8380:50 at Immediate._onImmediate (node:internal/deps/undici/undici:8411:13) at processImmediate (node:internal/timers:476:21) { code: 'UND_ERR_CONNECT_TIMEOUT' } } [Nest] 91399 - 07/03/2023, 5:15:07 PM ERROR [ChatService] TypeError: fetch failed

因有全局设置
