### ISSUE TITLE
执行pnpm run start，一直报下面的错误

### ISSUE THREAD

**Issue by ljgeneral** [chatbi/chatbi#1]
file:///Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@aigcaas+chatgpt@5.2.4/node_modules/@aigcaas/chatgpt/src/chatgpt-api.ts:128
      throw new Error('Invalid environment; fetch is not defined')
            ^
Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@aigcaas+chatgpt@5.2.4/node_modules/@aigcaas/chatgpt/src/chatgpt-api.ts:128:13)
    at OpenAI.init (file:///Users/hxl/Sites/chatbi/chatbi/src/ai/api/openai.ts:11:16)
    at new DataQuestionAgent (file:///Users/hxl/Sites/chatbi/chatbi/src/ai/agent/data-question-agent.ts:33:18)
    at Injector.instantiateClass (/Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@nestjs+core@9.4.0_@nestjs+common@9.4.0_@nestjs+platform-express@9.4.0_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:351:19)
    at callback (/Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@nestjs+core@9.4.0_@nestjs+common@9.4.0_@nestjs+platform-express@9.4.0_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:56:45)
    at Injector.resolveConstructorParams (/Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@nestjs+core@9.4.0_@nestjs+common@9.4.0_@nestjs+platform-express@9.4.0_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:136:24)
    at Injector.loadInstance (/Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@nestjs+core@9.4.0_@nestjs+common@9.4.0_@nestjs+platform-express@9.4.0_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:61:13)
    at Injector.loadProvider (/Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@nestjs+core@9.4.0_@nestjs+common@9.4.0_@nestjs+platform-express@9.4.0_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:88:9)
    at /Users/hxl/Sites/chatbi/chatbi/node_modules/.pnpm/@nestjs+core@9.4.0_@nestjs+common@9.4.0_@nestjs+platform-express@9.4.0_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)

**Comment by yugasun** [comment]
Nodejs 版本需要 >= `18`，参考项目中文件：https://github.com/chatbi/chatbi/blob/main/.node-version
